name: Snowflake CLI Workflow
on: [push]
jobs:
 run-snowflake-cli:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Code
       uses: actions/checkout@v4
     - name: Install Snowflake CLI
       uses: snowflakedb/snowflake-cli-action@v1.5
       with:
         cli-version: "3.6.0"
     - name: Execute Snowflake Command
       env:
         SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
         SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
         SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}
       run: |
         snow --version
         snow connection test -x
